# Generated by Django 3.0.6 on 2020-09-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=64),
        ),
    ]
